version: '3'
services:
  app:
    build: .
    container_name: "rails-actioncable_app"
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/rails-actioncable
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: "rails-actioncable_db"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  mysql-data:
