default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: db

development:
  <<: *default
  database: rails-actioncable_development

test:
  <<: *default
  database: rails-actioncable_test

production:
  <<: *default
  database: rails-actioncable_production
  username: rails-actioncable
  password: <%= ENV['RAILS-ACTIONCABLE_DATABASE_PASSWORD'] %>
